// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/streaming.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityRequest) Reset() {
	*x = CityRequest{}
	mi := &file_proto_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityRequest) ProtoMessage() {}

func (x *CityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityRequest.ProtoReflect.Descriptor instead.
func (*CityRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *CityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type WeatherUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Condition     string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherUpdate) Reset() {
	*x = WeatherUpdate{}
	mi := &file_proto_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherUpdate) ProtoMessage() {}

func (x *WeatherUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherUpdate.ProtoReflect.Descriptor instead.
func (*WeatherUpdate) Descriptor() ([]byte, []int) {
	return file_proto_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherUpdate) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherUpdate) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *WeatherUpdate) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

var File_proto_streaming_proto protoreflect.FileDescriptor

const file_proto_streaming_proto_rawDesc = "" +
	"\n" +
	"\x15proto/streaming.proto\x12\tstreaming\"!\n" +
	"\vCityRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"c\n" +
	"\rWeatherUpdate\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature2X\n" +
	"\x0eWeatherService\x12F\n" +
	"\x10GetWeatherStream\x12\x16.streaming.CityRequest\x1a\x18.streaming.WeatherUpdate0\x01B0Z.distributed-systems/grpc-streaming/proto;protob\x06proto3"

var (
	file_proto_streaming_proto_rawDescOnce sync.Once
	file_proto_streaming_proto_rawDescData []byte
)

func file_proto_streaming_proto_rawDescGZIP() []byte {
	file_proto_streaming_proto_rawDescOnce.Do(func() {
		file_proto_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_proto_rawDesc), len(file_proto_streaming_proto_rawDesc)))
	})
	return file_proto_streaming_proto_rawDescData
}

var file_proto_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_streaming_proto_goTypes = []any{
	(*CityRequest)(nil),   // 0: streaming.CityRequest
	(*WeatherUpdate)(nil), // 1: streaming.WeatherUpdate
}
var file_proto_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.WeatherService.GetWeatherStream:input_type -> streaming.CityRequest
	1, // 1: streaming.WeatherService.GetWeatherStream:output_type -> streaming.WeatherUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_streaming_proto_init() }
func file_proto_streaming_proto_init() {
	if File_proto_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_proto_rawDesc), len(file_proto_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streaming_proto_goTypes,
		DependencyIndexes: file_proto_streaming_proto_depIdxs,
		MessageInfos:      file_proto_streaming_proto_msgTypes,
	}.Build()
	File_proto_streaming_proto = out.File
	file_proto_streaming_proto_goTypes = nil
	file_proto_streaming_proto_depIdxs = nil
}
